name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node
      - run: npx supabase@latest start
        env:
          SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
